# Generated by Django 5.1.2 on 2024-12-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_comment_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
    ]
