# Generated by Django 5.1.2 on 2024-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_reaction_unique_together'),
        ('vote', '0005_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nominee_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together={('category', 'nominee'), ('category', 'nominee_name')},
        ),
    ]
